name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug
      env:
        PACKAGE_REQUIREMENTS: kivy,kivymd,requests,pyrebase4,plyer,urllib3,charset-normalizer,idna,certifi
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
